version: '3.8'
services:
  db-mysql:
    image: mysql:5.7.40
    restart: always
    environment:
      MYSQL_DATABASE: laptopshop  # Đổi từ "root" thành tên database hợp lý
      MYSQL_ROOT_PASSWORD: mypassword  # Đặt mật khẩu hoặc dùng MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3309:3306"
    expose:
      - "3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always  # Đảm bảo app restart nếu gặp lỗi
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/laptopshop
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mypassword  # Nếu bạn đặt MYSQL_ALLOW_EMPTY_PASSWORD, có thể để trống
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db-mysql
