server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
  session: #config session
    store-type: jdbc
    timeout: 30m
    jdbc:
      initialize-schema: always
  #server.servlet.session.timeout
  #spring.session.jdbc.table-name=SPRING_SESSION

  servlet:
    multipart:
      max-file-size: 50MB #default = 1MB
      max-request-size: 50MB #default = 10 MB (form data)
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/laptopshop
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

#  mvc:
#    view:
#      prefix: /WEB-INF/view/ #tự động vào đường dẫn này để tìm kiếm view
#      suffix: .jsp #chỉ cần khai báo tên file đuôi .jsp sẽ được tự động thêm vào



#  jpa:
#    show-sql: true





